version: "3.9"
services:
  node:
    build: .
    image: andrey93it/rss-node
    networks:
      - app
    ports:
      - ${APP_PORT}:${PORT}
    volumes:
      - ./src:/usr/app/src/
      - ./logs:/usr/app/logs/
    depends_on:
      - db
    restart: always
  db:
    build: ./database
    image: andrey93it/rss-db
    networks:
      - app
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${DB_PORT}:${POSTGRES_PORT}
    restart: always

networks:
  app: